import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const adminUserActionModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalContent: {
    width: "88%",
    maxWidth: 420,
    alignSelf: "center",
    padding: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: themes.borderStrong,
    backgroundColor: themes.backgroundElevated,
  },
  modalTitle: {
    marginBottom: 16,
    textAlign: "center",
    fontSize: 20,
    fontFamily: "Oswald_600SemiBold",
    color: themes.vegasGold,
  },
  modalUserInfo: {
    marginBottom: 20,
  },
  modalUserName: {
    marginBottom: 4,
    fontSize: 16,
    fontFamily: "Inter_600SemiBold",
    color: themes.white,
  },
  modalUserEmail: {
    marginBottom:  16,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: themes.textSecondary,
  },
  confirmationText: {
    marginBottom: 8,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color: themes.white,
  },
  warningText: {
    marginBottom: 8,
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: themes.danger,
  },
  currentRole: {
    marginBottom:  12,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color:  themes.white,
  },
  roleLabel: {
    marginBottom: 8,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color: themes.textSecondary,
  },
  permissionToggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: themes.borderStrong,
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  permissionLabel: {
    fontSize: 16,
    fontFamily: "Inter_500Medium",
    color: themes.white,
    flexShrink: 1,
    paddingRight: 8,
  },
  permissionValue: {
    fontSize: 14,
    fontFamily: "Oswald_500Medium",
    color: themes.vegasGold,
  },
  capacityRow: {
    marginBottom: 12,
    gap: 8,
  },
  capacityStepper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  capacityButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    alignItems: "center",
    justifyContent: "center",
  },
  capacityButtonText: {
    fontSize: 20,
    fontFamily: "Oswald_500Medium",
    color: themes.vegasGold,
  },
  capacityValue: {
    minWidth: 30,
    textAlign: "center",
    fontSize: 18,
    fontFamily: "Inter_600SemiBold",
    color: themes.white,
  },
  modalPickerContainer: {
    marginBottom: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.borderStrong,
    backgroundColor: themes.backgroundSoft,
    overflow: "hidden",
  },
  modalPicker: {
    color: themes.white,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cancelButton: {
    flex: 1,
    padding: 12,
    marginRight: 8,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: themes.backgroundSoft,
    borderWidth: 1,
    borderColor: themes.borderStrong,
  },
  confirmButton: {
    flex: 1,
    padding: 12,
    marginLeft: 8,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: themes.vegasGold,
  },
  removalButton: {
    flex:  1,
    padding: 12,
    marginLeft: 8,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: themes.danger,
  },
  buttonText: {
    fontSize: 14,
    fontFamily: "Oswald_500Medium",
    color: themes.textPrimary,
  },
});