import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const masterAdminManageCourses = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    backgroundColor: "transparent",
  },
  headerSection: {
    paddingBottom: 20,
  },
  courseSection: {
    flex: 1,
    paddingHorizontal: 12,
    backgroundColor: "transparent",
  },
  footerSection: {
    paddingTop: 20,
    paddingBottom: 10,
  },
  pageTitle: {
    marginBottom: 24,
    textAlign: "center",
    fontSize: 40,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  searchIcon: {
    marginRight: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  tableSection: {
    flex: 1,
    marginTop: 8,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: "#FF4444",
    textAlign: "center",
    marginBottom: 20,
  },
  retryButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: themes.vegasGold,
    borderRadius: 6,
  },
  retryButtonText: {
    fontSize: 16,
    fontFamily: "Chakra-Medium",
    color: themes.black,
  },

  // Filter styles
  filterContainer: {
    flex: 1,
    padding: 16,
    marginBottom: 16,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: "transparent",
    borderColor: themes.vegasGold,
  },
  filterSectionTitle: {
    marginBottom: 16,
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  filterRow: {
    flexDirection: "row",
    marginBottom: 12,
  },
  filterItem: {
    flex: 1,
    marginHorizontal: 4,
  },
  filterLabel: {
    marginBottom: 8,
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  searchInput: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: "transparent",
    color: themes.white,
    fontFamily: "Chakra-Regular",
  },
  filterPickerContainer: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  filterPicker: {
    color: themes.white,
  },

  tableContainer: {
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  tableSectionTitle: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: themes.vegasGold,
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  listContent: {
    paddingBottom: 16,
  },
  row: {
    flex: 1,
    flexDirection: "row",
    padding: 16,
    alignItems: "center",
  },
  info: {
    flex: 3,
  },
  name: {
    marginBottom: 4,
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  description: {
    marginBottom: 8,
    fontSize: 18,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.8,
  },
  details: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  badge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    marginRight: 12,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  badgeText: {
    fontSize: 18,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  actions: {
    flex: 1,
    flexDirection: "column",
  },
  courseButton: {
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    padding: 8,
    backgroundColor: "transparent",
  },
  actionButton: {
    flex: 1,
    alignItems: "center",
    padding: 12,
    margin: 8,
    borderRadius: 15,
    backgroundColor: themes.vegasGold,
  },
  actionText: {
    marginLeft: 6,
    fontSize: 14,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
  },
  removeText: {
    color: "#FF4444",
  },
  separator: {
    height: 1,
    backgroundColor: themes.vegasGold,
  },
  emptyState: {
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyStateText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.5,
  },

  // RoleSelection Modal Styles
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  modalContent: {
    width: "80%",
    alignSelf: "center",
    padding: 20,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  modalTitle: {
    marginBottom: 16,
    textAlign: "center",
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  modalUserInfo: {
    marginBottom: 20,
  },
  modalUserName: {
    marginBottom: 4,
    fontSize: 24,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  modalUserEmail: {
    marginBottom: 16,
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.8,
  },
  confirmationText: {
    marginBottom: 8,
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  warningText: {
    marginBottom: 8,
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: "#FF4444",
  },
  currentRole: {
    marginBottom: 12,
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  modalLabel: {
    marginBottom: 8,
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  modalPickerContainer: {
    marginBottom: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  modalPicker: {
    color: themes.white,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  cancelButton: {
    flex: 1,
    padding: 12,
    marginRight: 8,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: themes.vegasGold,
  },
  confirmButton: {
    flex: 1,
    padding: 12,
    marginLeft: 12,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: themes.vegasGold,
  },
  removalButton: {
    flex: 1,
    padding: 12,
    marginLeft: 8,
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: themes.vegasGold,
  },
  buttonText: {
    fontSize: 24,
    fontFamily: "Chakra-BoldItalic",
    color: themes.white,
  },

  // Instructor Selection Modal Styles
  contentContainer: {
    minHeight: 200,
  },
  createSection: {
    padding: 4,
  },
  inputDescription: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 20,
    opacity: 0.9,
  },
  savingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
    gap: 8,
  },
  savingText: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  footerInfoInstructor: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: themes.vegasGold,
  },
  footerTextInstructor: {
    fontSize: 12,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    textAlign: "center",
    lineHeight: 16,
    opacity: 0.8,
  },
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  emptyStateIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
    textAlign: "center",
    marginBottom: 12,
  },
  emptyStateDescription: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 24,
    opacity: 0.9,
  },
  footerInfo: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: themes.vegasGold,
  },
  footerText: {
    fontSize: 12,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    textAlign: "center",
    lineHeight: 16,
  },
});
