import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const profileScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  profileContentContainer: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-evenly",
    gap: 30,
    paddingHorizontal: 20,
  },
  profileName: {
    fontSize: 64,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
    textAlign: "center",
    borderWidth: 1,
    padding: 10,
  },
  profilePictureContainer: {
    width: 300,
    height: 300,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 150,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  profileBioContainer: {
    flexDirection: "column",
    justifyContent: "flex-start",
    width: 700,
    alignSelf: "center",
    borderRadius: 30,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  profileBioText: {
    fontSize: 24,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    paddingLeft: 20,
    paddingBottom: 10,
    paddingTop: 10,
    borderBottomColor: themes.vegasGold,
    borderBottomWidth: 1,
  },
  profileBioTextBottom: {
    fontSize: 24,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    paddingLeft: 20,
    paddingBottom: 10,
    paddingTop: 10,
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 20,
  },
  button: {
    padding: 10,
    borderRadius: 30,
    width: 300,
    height: 100,
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: themes.vegasGold,
  },
  buttonText: {
    fontSize: 24,
    fontFamily: "Chakra-BoldItalic",
    color: themes.white,
  },

  //EditModalStyles
  editModalContainer: {
    flex: 1,
    backgroundColor: themes.black,
  },
  editModalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  editModalContent: {
    width: "90%",
    maxHeight: "80%",
    padding: 20,
    borderWidth: 2,
    borderRadius: 20,
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  editModalTitle: {
    marginBottom: 20,
    fontSize: 28,
    fontFamily: "Chakra-BoldItalic",
    textAlign: "center",
    color: themes.vegasGold,
  },
  editModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  formGroup: {
    marginBottom: 20,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 20,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  closeButtonText: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  title: {
    fontSize: 32,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
  },
  modalContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  fieldContainer: {
    marginBottom: 24,
  },
  label: {
    marginBottom: 8,
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  input: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderRadius: 10,
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
    color: themes.white,
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  inputLabel: {
    marginBottom: 8,
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  inputError: {
    borderWidth: 2,
    borderColor: "#FF4444",
  },
  inputFocused: {
    borderWidth: 2,
    borderColor: themes.vegasGold,
  },
  errorText: {
    marginTop: 8,
    textAlign: "left",
    fontSize: 16,
    fontFamily: "Chakra-Bold",
    color: "#FF4444",
  },
  modalButtonContainer: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 16,
    borderTopWidth: 1,
    backgroundColor: themes.black,
    borderTopColor: themes.vegasGold,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 56,
    borderWidth: 1,
  },
  editModalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    gap: 16,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: themes.vegasGold,
    minHeight: 48,
  },
  editModalButtonText: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  datePickerButton: {
    justifyContent: "center",
  },
  datePickerText: {
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  datePickerPlaceholder: {
    fontFamily: "Chakra-Regular",
    fontSize: 18,
    color: themes.vegasGold,
  },
  spacingSmall: {
    marginBottom: 8,
  },
  spacingMedium: {
    marginBottom: 16,
  },
  spacingLarge: {
    marginBottom: 24,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 100,
  },
  characterCount: {
    fontSize: 12,
    color: '#666',
    textAlign: 'right',
    marginTop: 4,
  },
  validationIndicator: {
    position: "absolute",
    right: 16,
    top: "50%",
    marginTop: -10,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  validationSuccess: {
    backgroundColor: "#4CAF50",
  },
  validationError: {
    backgroundColor: "#FF4444",
  },
  validationText: {
    fontSize: 12,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
});
