import { themes } from "@/src/context/themes";
import { StyleSheet } from "react-native";

export const registerScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  backButtonContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 20,
  },
  registerScreenContentContainer: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    gap: 50,
  },
  image: {
    width: 300,
    height: 300,
  },
  nameInputBoxContainer: {
    flexDirection: "row",
    gap: 50,
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  nameInputBox: {
    width: "33%",
    paddingHorizontal: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
    color: themes.vegasGold,
    fontSize: 36,
    fontFamily: "Chakra-Italic",
  },
  textInputBox: {
    height: 90,
    width: "75%",
    paddingHorizontal: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
    color: themes.vegasGold,
    fontSize: 36,
    fontFamily: "Chakra-Italic",
  },
  signUpButton: {
    height: 80,
    width: "60%",
    backgroundColor: themes.vegasGold,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  signUpButtonText: {
    fontFamily: "Chakra-semiBoldItalic",
    fontSize: 32,
    color: themes.white,
  },
  orContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 30,
  },
  orText: {
    fontFamily: "Chakra-semiBoldItalic",
    fontSize: 36,
    color: themes.white,
  },
  horizontalLine: {
    flex: 1,
    borderBottomColor: themes.vegasGold,
    borderBottomWidth: 2,
  },
  welcomeContainer: {
    marginVertical: 20,
    marginHorizontal: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  welcomeText: {
    textAlign: "center",
    lineHeight: 28,
    marginBottom: 8,
    letterSpacing: 0.5,
    fontSize: 22,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  welcomeSubtext: {
    textAlign: "center",
    lineHeight: 22,
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  modalContent: {
    width: "85%",
    maxWidth: 450,
    padding: 20,
    backgroundColor: themes.black,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: themes.vegasGold,
  },
  modalTitle: {
    marginBottom: 20,
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
    textAlign: "center",
  },
  welcomeTitle: {
    textAlign: "center",
    marginBottom: 8,
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  companyName: {
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  buttonContainer: {
    gap: 16,
    marginBottom: 20,
  },
  roleButton: {
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 15,
    backgroundColor: themes.vegasGold,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  recommendedButton: {
    backgroundColor: themes.vegasGold,
    borderWidth: 2,
    borderColor: themes.vegasGold,
    shadowColor: themes.vegasGold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  disabledButton: {
    opacity: 0.6,
  },

  buttonContent: {
    alignItems: "center",
    width: "100%",
  },
  buttonHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    gap: 12,
  },
  roleIcon: {
    fontSize: 24,
  },
  buttonTitle: {
    fontSize: 22,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  buttonDescription: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 8,
  },
  recommendedBadge: {
    backgroundColor: themes.black,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  recommendedText: {
    fontSize: 12,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 8,
  },
  loadingText: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  footerInfo: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: themes.vegasGold,
  },
  footerText: {
    fontSize: 12,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    textAlign: "center",
    lineHeight: 16,
  },
});
