import { themes } from "@/src/context/themes";
import { StyleSheet } from "react-native";

export const calendarScreenStyles = StyleSheet.create({
  container: {
    flex:  1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent'
  },
  pageScroll: {
    flex: 1,
  },
  pageScrollContent: {
    paddingBottom: 24,
    paddingHorizontal: 20,
  },
  calendarContainer: {
    width: "100%",
    alignSelf: "stretch" as const,
    borderRadius: 20,
    overflow: "hidden",
    marginVertical: 16,
    marginHorizontal: 0,
    borderWidth: 2,
    borderColor: themes.white,
  },
  scheduleContainer: {
    borderTopLeftRadius: 100,
    borderTopRightRadius: 100,
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 100,
    marginTop: 30,
    marginBottom: 16,
    paddingTop: 8,
    paddingRight: 16,
    paddingLeft: 16,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  scheduleList: {
    minHeight: 220,
    maxHeight: 420,
  },
  scheduleText: {
    fontSize: 48,
    fontFamily: "Chakra-BoldItalic",
    marginBottom: 16,
    textAlign: 'center',
    color: themes.white,
  },
  sessionText: {
    fontSize: 28,
    fontFamily: "Chakra-Regular",
    color: themes.white
  },
  sessionCard: {
    flexDirection: "row",
    borderRadius: 15,
    padding: 16,  
    marginBottom: 16,
    borderWidth: 1,
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  buttonContainer: {
    flexDirection:  "row",
    justifyContent: "center",
    marginTop: 16,
  },
  actionButton: {
    width: "75%",
    marginHorizontal: 8,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  actionButtonText: {
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  actionButtonActive: {
    opacity: 0.7,
    backgroundColor: themes.black
  },
  actionButtonTextActive: {
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  addButtonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 16,
  },
  addButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 16,
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  addButtonText: {
    fontSize: 32,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  availabilityCardSelected: {
    borderWidth: 2,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  availabilityInfo: {
    flex: 1,
    justifyContent: "space-between"
  },
  selectionIndicator: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: themes.vegasGold,
  },
  selectionIndicatorText: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.black,
  },
  availabilityActionButtons: {
    flexDirection: "row",
    justifyContent:  "space-between",
    marginTop: 16,
    gap: 12,
  },
  updateButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  updateButtonText: {
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  }, 
  deleteButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  deleteButtonText: {
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  weeklyScheduleContainer: {
    marginTop: 16,
  },
  dayScheduleContainer: {
    marginBottom: 20,
    paddingBottom: 16,
  },
  dayTitle: {
    marginBottom: 8,
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  noAvailabilityText: {
    paddingLeft: 12,
    fontSize: 28,
    textAlign: "center",
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  instructorFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  instructorFilterLabel: {
    fontSize: 22,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  instructorFilterPickerWrap: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    borderRadius: 10,
    backgroundColor: themes.black,
    justifyContent: "center",
  },
  instructorFilterPicker: {
    color: themes.white,
  },
  sectionSubtitle: {
    marginBottom: 12,
    fontSize: 28,
    textAlign: "center",
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
  },
  hintText: {
    marginTop: 8,
    textAlign: "center",
    fontSize: 24,
    fontFamily: "Chakra-Italic",
    color: themes.white,
  },
  errorText: {
    fontSize: 16,
    marginTop: 8,
    textAlign: "center",
    fontFamily: "Chakra-Bold",
    color: "#FF4444",
  },
  scrollContentContainer: {
    paddingBottom: 96,
  },
  monthNavRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 12,
    minHeight: 52,
  },
  monthNavButton: {
    minWidth: 56,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  monthNavButtonText: {
    fontSize: 18,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  monthTitle: {
    fontSize: 22,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
    flex: 1,
    textAlign: "center",
  },
});