import { themes } from "@/src/context/themes";
import { StyleSheet } from "react-native";

export const calendarScreenStyles = StyleSheet.create({
  container: {
    flex:  1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent'
  },
  pageScroll: {
    flex: 1,
  },
  pageScrollContent: {
    paddingBottom: 24,
    paddingHorizontal: 16,
  },
  calendarContainer: {
    width: "100%",
    alignSelf: "stretch" as const,
    borderRadius: 16,
    overflow: "hidden",
    marginVertical: 16,
    marginHorizontal: 0,
    borderWidth: 1,
    borderColor: themes.borderStrong,
  },
  scheduleContainer: {
    borderRadius: 16,
    marginTop: 16,
    marginBottom: 16,
    paddingTop: 8,
    paddingRight: 16,
    paddingLeft: 16,
    borderWidth: 1,
    borderColor: themes.borderStrong,
    backgroundColor: themes.backgroundElevated,
  },
  scheduleList: {
    minHeight: 220,
    maxHeight: 420,
  },
  scheduleText: {
    fontSize: 24,
    fontFamily: "Oswald_500Medium",
    marginBottom: 12,
    textAlign: 'center',
    color: themes.white,
  },
  sessionText: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: themes.textPrimary,
    lineHeight: 20,
  },
  sessionTitleText: {
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    color: themes.textPrimary,
    lineHeight: 22,
  },
  sessionInfo: {
    flex: 1,
    gap: 4,
  },
  sessionCard: {
    flexDirection: "row",
    borderRadius: 12,
    padding: 16,  
    marginBottom: 16,
    borderWidth: 1,
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: themes.backgroundElevated,
    borderColor: themes.borderStrong,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 16,
  },
  actionButton: {
    minWidth: 150,
    marginHorizontal: 4,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  actionButtonText: {
    fontSize: 14,
    fontFamily: "Oswald_500Medium",
    color: themes.textPrimary,
  },
  actionButtonActive: {
    backgroundColor: themes.backgroundSoft,
  },
  actionButtonTextActive: {
    fontSize: 16,
    fontFamily: "Oswald_500Medium",
    color: themes.white,
  },
  addButtonContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 16,
  },
  addButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 16,
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  addButtonText: {
    fontSize: 16,
    fontFamily: "Oswald_500Medium",
    color: themes.textPrimary,
  },
  availabilityCardSelected: {
    borderWidth: 2,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  availabilityInfo: {
    flex: 1,
    justifyContent: "space-between"
  },
  selectionIndicator: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: themes.vegasGold,
  },
  selectionIndicatorText: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: themes.black,
  },
  availabilityActionButtons: {
    flexDirection: "row",
    justifyContent:  "space-between",
    marginTop: 16,
    gap: 12,
  },
  updateButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  updateButtonText: {
    fontSize: 14,
    fontFamily: "Oswald_500Medium",
    color: themes.white,
  }, 
  deleteButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    backgroundColor: themes.black,
    borderColor: themes.vegasGold,
  },
  deleteButtonText: {
    fontSize: 14,
    fontFamily: "Oswald_500Medium",
    color: themes.white,
  },
  weeklyScheduleContainer: {
    marginTop: 16,
  },
  dayScheduleContainer: {
    marginBottom: 20,
    paddingBottom: 16,
  },
  dayTitle: {
    marginBottom: 8,
    fontSize: 18,
    fontFamily: "Oswald_500Medium",
    color: themes.vegasGold,
  },
  noAvailabilityText: {
    paddingLeft: 12,
    fontSize: 14,
    textAlign: "center",
    fontFamily: "Inter_400Regular",
    color: themes.textSecondary,
  },
  instructorFilterRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  instructorFilterLabel: {
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color: themes.white,
  },
  instructorFilterPickerWrap: {
    flex: 1,
    minHeight: 44,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    borderRadius: 10,
    backgroundColor: themes.black,
    justifyContent: "center",
  },
  instructorFilterPicker: {
    color: themes.white,
  },
  sectionSubtitle: {
    marginBottom: 12,
    fontSize: 20,
    textAlign: "center",
    fontFamily: "Oswald_500Medium",
    color: themes.vegasGold,
  },
  hintText: {
    marginTop: 8,
    textAlign: "center",
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: themes.textSecondary,
  },
  errorText: {
    fontSize: 16,
    marginTop: 8,
    textAlign: "center",
    fontFamily: "Inter_600SemiBold",
    color: themes.danger,
  },
  bookingActionWrap: {
    justifyContent: "center",
    paddingRight: 10,
  },
  scrollContentContainer: {
    paddingBottom: 96,
  },
  monthNavRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 12,
    minHeight: 52,
  },
  monthNavButton: {
    minWidth: 56,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  monthNavButtonText: {
    fontSize: 14,
    fontFamily: "Oswald_500Medium",
    color: themes.vegasGold,
  },
  monthTitle: {
    fontSize: 20,
    fontFamily: "Oswald_500Medium",
    color: themes.vegasGold,
    flex: 1,
    textAlign: "center",
  },
});