"""Updated invite code model to include a role field

Revision ID: 11d1c78a3883
Revises: 17029079ee97
Create Date: 2025-12-18 17:56:08.072868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d1c78a3883'
down_revision: Union[str, Sequence[str], None] = '17029079ee97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_invite_codes', sa.Column('role', sa.Enum('STUDENT', 'INSTRUCTOR', 'ADMIN', 'MASTERADMIN', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_invite_codes', 'role')
    # ### end Alembic commands ###
