"""Updated user model to have a student_enrollment relationship

Revision ID: 17029079ee97
Revises: 3c48a78590c6
Create Date: 2025-10-16 21:13:04.077149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17029079ee97'
down_revision: Union[str, Sequence[str], None] = '3c48a78590c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
