"""Now I have added Session forms and Course drill forms

Revision ID: 3c48a78590c6
Revises: ada12bdd8035
Create Date: 2025-10-15 11:21:50.027916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c48a78590c6'
down_revision: Union[str, Sequence[str], None] = 'ada12bdd8035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_drill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('drill_name', sa.String(length=100), nullable=False),
    sa.Column('drill_type', sa.Enum('TIME', 'SCORE', 'ACCURACY', name='drilltype'), nullable=False),
    sa.Column('standard_value', sa.Float(), nullable=False),
    sa.Column('standard_unit', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_drill_course_id'), 'course_drill', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_drill_id'), 'course_drill', ['id'], unique=False)
    op.create_table('student_drill_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drill_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['drill_id'], ['course_drill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_drill_results_drill_id'), 'student_drill_results', ['drill_id'], unique=False)
    op.create_index(op.f('ix_student_drill_results_id'), 'student_drill_results', ['id'], unique=False)
    op.create_index(op.f('ix_student_drill_results_student_id'), 'student_drill_results', ['student_id'], unique=False)
    op.create_table('session_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Enum('POOR', 'AVERAGE', 'GREAT', name='sleepquality'), nullable=True),
    sa.Column('has_eaten', sa.Boolean(), nullable=True),
    sa.Column('has_pain', sa.Boolean(), nullable=True),
    sa.Column('pain_description', sa.String(length=255), nullable=True),
    sa.Column('pre_stress_level', sa.Enum('LOW', 'MODERATE', 'HIGH', name='prestresslevel'), nullable=True),
    sa.Column('motivation_before', sa.Integer(), nullable=True),
    sa.Column('post_stress_level', sa.Enum('LESS_STRESSED', 'SAME', 'MORE_STRESSED', name='poststresslevel'), nullable=True),
    sa.Column('motivation_after', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('advance_student', sa.Boolean(), nullable=False),
    sa.Column('instructor_notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_forms_course_id'), 'session_forms', ['course_id'], unique=False)
    op.create_index(op.f('ix_session_forms_id'), 'session_forms', ['id'], unique=False)
    op.create_index(op.f('ix_session_forms_instructor_id'), 'session_forms', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_session_forms_session_id'), 'session_forms', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_forms_student_id'), 'session_forms', ['student_id'], unique=False)
    op.create_table('test_session_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('sleep_hours', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Enum('POOR', 'AVERAGE', 'GREAT', name='sleepquality'), nullable=True),
    sa.Column('has_eaten', sa.Boolean(), nullable=True),
    sa.Column('has_pain', sa.Boolean(), nullable=True),
    sa.Column('pain_description', sa.String(length=255), nullable=True),
    sa.Column('pre_stress_level', sa.Enum('LOW', 'MODERATE', 'HIGH', name='prestresslevel'), nullable=True),
    sa.Column('motivation_before', sa.Integer(), nullable=True),
    sa.Column('post_stress_level', sa.Enum('LESS_STRESSED', 'SAME', 'MORE_STRESSED', name='poststresslevel'), nullable=True),
    sa.Column('motivation_after', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('highlight', sa.String(length=255), nullable=True),
    sa.Column('advance_student', sa.Boolean(), nullable=False),
    sa.Column('instructor_notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_session_forms_course_id'), 'test_session_forms', ['course_id'], unique=False)
    op.create_index(op.f('ix_test_session_forms_id'), 'test_session_forms', ['id'], unique=False)
    op.create_index(op.f('ix_test_session_forms_instructor_id'), 'test_session_forms', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_test_session_forms_session_id'), 'test_session_forms', ['session_id'], unique=False)
    op.create_index(op.f('ix_test_session_forms_student_id'), 'test_session_forms', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_session_forms_student_id'), table_name='test_session_forms')
    op.drop_index(op.f('ix_test_session_forms_session_id'), table_name='test_session_forms')
    op.drop_index(op.f('ix_test_session_forms_instructor_id'), table_name='test_session_forms')
    op.drop_index(op.f('ix_test_session_forms_id'), table_name='test_session_forms')
    op.drop_index(op.f('ix_test_session_forms_course_id'), table_name='test_session_forms')
    op.drop_table('test_session_forms')
    op.drop_index(op.f('ix_session_forms_student_id'), table_name='session_forms')
    op.drop_index(op.f('ix_session_forms_session_id'), table_name='session_forms')
    op.drop_index(op.f('ix_session_forms_instructor_id'), table_name='session_forms')
    op.drop_index(op.f('ix_session_forms_id'), table_name='session_forms')
    op.drop_index(op.f('ix_session_forms_course_id'), table_name='session_forms')
    op.drop_table('session_forms')
    op.drop_index(op.f('ix_student_drill_results_student_id'), table_name='student_drill_results')
    op.drop_index(op.f('ix_student_drill_results_id'), table_name='student_drill_results')
    op.drop_index(op.f('ix_student_drill_results_drill_id'), table_name='student_drill_results')
    op.drop_table('student_drill_results')
    op.drop_index(op.f('ix_course_drill_id'), table_name='course_drill')
    op.drop_index(op.f('ix_course_drill_course_id'), table_name='course_drill')
    op.drop_table('course_drill')
    # ### end Alembic commands ###
