"""Update course model with S3 keys

Revision ID: 3ca5dd2c2c98
Revises: b6759df743c4
Create Date: 2025-08-27 15:05:13.308260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca5dd2c2c98'
down_revision: Union[str, Sequence[str], None] = 'b6759df743c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('pdf_s3_key', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('instructor_script_s3_key', sa.String(length=500), nullable=True))
    op.drop_column('courses', 'pdf_url')
    op.drop_column('courses', 'instructor_script_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('instructor_script_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('courses', 'instructor_script_s3_key')
    op.drop_column('courses', 'pdf_s3_key')
    # ### end Alembic commands ###
