"""Added course relationship to sessions

Revision ID: 4d20a90b4d2a
Revises: b0ff67bda9d3
Create Date: 2025-08-13 15:07:51.245600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d20a90b4d2a'
down_revision: Union[str, Sequence[str], None] = 'b0ff67bda9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'course_id')
    # ### end Alembic commands ###
