"""Added enrollment relationship to session

Revision ID: 517e4a8b1953
Revises: c5c56e64725a
Create Date: 2025-08-13 13:57:25.257787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517e4a8b1953'
down_revision: Union[str, Sequence[str], None] = 'c5c56e64725a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('enrollment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'student_enrollments', ['enrollment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'enrollment_id')
    # ### end Alembic commands ###
