"""Added IN_PROGRESS to session status enum

Revision ID: 62d87e46dd30
Revises: 4d20a90b4d2a
Create Date: 2025-08-14 11:55:25.047136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d87e46dd30'
down_revision: Union[str, Sequence[str], None] = '4d20a90b4d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
