"""Added IN_PROGRESS to session status enum

Revision ID: 63d9e6f887f6
Revises: 6d03e1d596f9
Create Date: 2025-08-14 12:12:33.352790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d9e6f887f6'
down_revision: Union[str, Sequence[str], None] = '6d03e1d596f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sessionstatus ADD VALUE 'in_progress'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
