"""Added IN_PROGRESS to session status enum

Revision ID: 6d03e1d596f9
Revises: 62d87e46dd30
Create Date: 2025-08-14 12:07:24.092551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d03e1d596f9'
down_revision: Union[str, Sequence[str], None] = '62d87e46dd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
