"""Finished implementing instructor_availability and events.

Revision ID: a382cfbfe3f2
Revises: 1ff2ac779b41
Create Date: 2025-07-17 10:18:12.816802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a382cfbfe3f2'
down_revision: Union[str, Sequence[str], None] = '1ff2ac779b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'created_by_user_id')
    op.drop_column('events', 'image')
    # ### end Alembic commands ###
