"""Session form and test form tables. Course drill tables.

Revision ID: ada12bdd8035
Revises: 3ca5dd2c2c98
Create Date: 2025-10-15 11:12:56.684328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada12bdd8035'
down_revision: Union[str, Sequence[str], None] = '3ca5dd2c2c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_enrollments', 'instructor_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_enrollments', sa.Column('instructor_notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
