"""Added Instructor_Availability Table

Revision ID: bbc6e66aad14
Revises: c8ee8e4a13bb
Create Date: 2025-07-30 11:41:28.392611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc6e66aad14'
down_revision: Union[str, Sequence[str], None] = 'c8ee8e4a13bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
