"""Fixed naming issue between event table and user table.

Revision ID: c8ee8e4a13bb
Revises: a382cfbfe3f2
Create Date: 2025-07-28 01:53:01.760557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ee8e4a13bb'
down_revision: Union[str, Sequence[str], None] = 'a382cfbfe3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'instructor_id')
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
