import { themes } from "@/src/context/themes";
import { StyleSheet } from "react-native";

export const loginScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 8,
    justifyContent: "center",
  },
  card: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(197,179,88,0.3)",
    backgroundColor: "rgba(8,8,8,0.78)",
    paddingTop: 28,
    paddingHorizontal: 20,
    paddingBottom: 24,
    gap: 14,
  },
  backButtonContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  loginScreenContentContainer: {
    gap: 12,
  },
  image: {
    width: 74,
    height: 74,
    resizeMode: "contain",
    borderRadius: 12,
    alignSelf: "center",
  },
  logoWrap: {
    alignItems: "center",
    gap: 8,
  },
  heading: { textAlign: "center" },
  subtitle: { textAlign: "center", color: themes.textSecondary },
  securityBadge: {
    alignSelf: "center",
    borderWidth: 1,
    borderColor: "rgba(197,179,88,0.34)",
    borderRadius: 999,
    backgroundColor: "rgba(197,179,88,0.1)",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  securityText: {
    color: themes.textPrimary,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  form: { gap: 12, marginTop: 8 },
  textInputBox: {
    minHeight: 52,
    width: "100%",
    maxWidth: 520,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.borderStrong,
    backgroundColor: themes.backgroundElevated,
    color: themes.textPrimary,
    fontSize: 16,
    fontFamily: "Inter_400Regular",
  },
  logInButton: {
    minHeight: 52,
    width: "100%",
    maxWidth: 520,
    backgroundColor: themes.vegasGold,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  logInButtonText: {
    fontFamily: "Oswald_500Medium",
    fontSize: 20,
    color: themes.black,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  forgotPasswordText: {
    fontFamily: "Inter_500Medium",
    fontSize: 15,
    color: themes.vegasGold,
    textAlign: "center",
    textDecorationLine: "underline",
    textDecorationColor: "rgba(197,179,88,0.7)",
  },
  orContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginVertical: 6,
  },
  orText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
    color: themes.textMuted,
  },
  horizontalLine: {
    flex: 1,
    borderBottomColor: themes.borderStrong,
    borderBottomWidth: 1,
  },
  registerPrompt: {
    textAlign: "center",
    color: themes.textSecondary,
  },
  registerLink: {
    color: themes.vegasGold,
    textDecorationLine: "underline",
  },
});
