import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const courseScreenStyles = StyleSheet.create({
  container: {
    flex:  1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scrollContainer: {
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
    padding: 16,
  },
  headerSection: {
    marginBottom: 24,
  },
  courseListSection: {
    marginBottom: 24,
  },
  actionsSection: {
    flex: 1,
  },
  pageTitle: {
    fontSize: 32,
    fontFamily: "Oswald_500Medium",
    textAlign: "center",
    color: themes.textPrimary,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize:  24,
    fontFamily: "Oswald_500Medium",
    textAlign: "center",
    color: themes.vegasGold,
    marginBottom: 16,
    marginLeft: 4,
  },
  statsContainer: {
    backgroundColor: themes.backgroundElevated,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: themes.borderStrong,
  },
  statRow: {
    flexDirection: "row",
    justifyContent:  "space-around",
  },
  statCard: {
    alignItems: "center",
    padding: 8,
  },
  statValue: {
    fontSize: 22,
    fontFamily: "Oswald_500Medium",
    color: themes.vegasGold,
  },
  statLabel:  {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: themes.textSecondary,
    textAlign: "center",
    marginTop: 4,
  },
  horizontalListContainer: {
    alignItems: "center",
  },
  horizontalListContent: {
    paddingRight: 16,
  },
  selectedCourseSection: {
    backgroundColor: themes.backgroundElevated,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: themes. vegasGold,
    overflow: "hidden",
  },
  selectedCourseHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor:  themes.vegasGold,
  },
  selectedCourseInfo: {
    flex: 1,
  },
  selectedCourseTitle: {
    fontSize: 24,
    textAlign: "center",
    fontFamily: "Oswald_500Medium",
    color: themes.white,
    marginBottom: 8,
  },
  selectedCourseDescription: {
    fontSize: 16,
    textAlign: "center",
    fontFamily: "Inter_400Regular",
    color: themes.textSecondary,
    marginBottom: 16,
  },
  selectedCourseMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  metaBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical:  6,
    backgroundColor: themes.vegasGold + "20",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    gap: 6,
  },
  metaBadgeText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.vegasGold,
    fontWeight: "600",
  },
  actionButtonsGrid: {
    padding: 20,
  },
  actionButtonsTitle: {
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
    marginBottom: 16,
    textAlign: "center",
  },
  actionButtonsRow: {
    flexDirection: "row",
    justifyContent:  "space-between",
    marginBottom:  12,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    alignItems: "center",
    padding: 20,
    borderRadius: 16,
    backgroundColor: themes.black + "60",
    borderWidth: 1,
    borderColor: themes.vegasGold + "40",
    minHeight: 120,
    justifyContent: "center",
  },
  actionButtonDisabled: {
    backgroundColor: themes.black + "30",
    borderColor: themes.white + "20",
    opacity: 0.6,
  },
  actionButtonTitle: {
    fontSize: 16,
    fontFamily: "Oswald_500Medium",
    color: themes.white,
    marginTop: 12,
    textAlign: "center",
  },
  actionButtonTitleDisabled: {
    color: themes.white + "60",
  },
  actionButtonSubtitle: {
    fontSize:  13,
    fontFamily: "Inter_400Regular",
    color: themes.textSecondary,
    marginTop: 4,
    textAlign: "center",
  },
  actionButtonSubtitleDisabled: {
    color:  themes.white + "40",
  },
  noSelectionContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(201, 176, 55, 0.05)",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: themes. vegasGold + "30",
    borderStyle: "dashed",
  },
  noSelectionText:  {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.7,
    textAlign: "center",
    marginTop: 12,
    lineHeight: 22,
  },
  loadingContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    height: 200,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.8,
  },
  errorContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    height: 200,
  },
  errorText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: "#FF4444",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 22,
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: themes.vegasGold,
    borderRadius: 8,
  },
  retryButtonText:  {
    fontSize: 16,
    fontFamily: "Chakra-Bold",
    color: themes.black,
  },
  emptyListContainer: {
    width: 280,
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyListText:  {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    textAlign: "center",
    color: themes.white,
    opacity: 0.7,
  },
});
