// src/styles/coursesStyles.ts

import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const coursesStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  scrollContainer: {
    flex: 1,
  },
  contentContainer: {
    flexGrow: 1,
    padding: 16,
  },
  headerSection: {
    marginBottom: 24,
  },
  courseListSection: {
    marginBottom: 24,
  },
  actionsSection: {
    flex: 1,
  },
  pageTitle: {
    fontSize: 48,
    fontFamily: "Chakra-Italic",
    textAlign: "center",
    color: themes.vegasGold,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 32,
    fontFamily: "Chakra-Bold",
    textAlign: "center",
    color: themes.vegasGold,
    marginBottom: 16,
    marginLeft: 4,
  },
  statsContainer: {
    backgroundColor: "transparent",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  statCard: {
    alignItems: "center",
    padding: 8,
  },
  statValue: {
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  statLabel: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    textAlign: "center",
    marginTop: 4,
  },
  horizontalListContainer: {
    alignItems: "center",
  },
  horizontalListContent: {
    paddingRight: 16,
  },
  courseCard: {
    width: 320,
    padding: 16,
    marginRight: 16,
    borderRadius: 16,
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  selectedCourseCard: {
    borderColor: themes.vegasGold,
    borderWidth: 2,
  },
  courseCardContent: {
    flex: 1,
  },
  courseHeader: {
    marginBottom: 12,
  },
  courseTitleSection: {
    marginBottom: 8,
  },
  courseTitle: {
    fontSize: 24,
    textAlign: "center",
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  courseDescription: {
    fontSize: 20,
    textAlign: "center",
    fontFamily: "Chakra-Regular",
    color: themes.white,
    marginBottom: 12,
  },
  courseInfo: {
    marginBottom: 12,
  },
  courseBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: themes.vegasGold + "20",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  badgeText: {
    fontSize: 16,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  selectedIndicator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "transparent",
    borderRadius: 8,
    gap: 8,
    marginTop: 4,
  },
  selectedText: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  selectedCourseSection: {
    backgroundColor: "transparent",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: themes.vegasGold,
    overflow: "hidden",
  },
  selectedCourseHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: themes.vegasGold,
  },
  selectedCourseInfo: {
    flex: 1,
  },
  selectedCourseTitle: {
    fontSize: 32,
    textAlign: "center",
    fontFamily: "Chakra-Bold",
    color: themes.white,
    marginBottom: 8,
  },
  selectedCourseDescription: {
    fontSize: 24,
    textAlign: "center",
    fontFamily: "Chakra-Italic",
    color: themes.white,
    marginBottom: 16,
  },
  selectedCourseMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 10,
  },
  metaBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: themes.vegasGold + "20",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    gap: 6,
  },
  metaBadgeText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.vegasGold,
    fontWeight: "600",
  },
  actionButtonsGrid: {
    padding: 20,
  },
  actionButtonsTitle: {
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
    marginBottom: 16,
    textAlign: "center",
  },
  actionButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    alignItems: "center",
    padding: 20,
    borderRadius: 16,
    backgroundColor: themes.black + "60",
    borderWidth: 1,
    borderColor: themes.vegasGold + "40",
    minHeight: 120,
    justifyContent: "center",
  },
  actionButtonDisabled: {
    backgroundColor: themes.black + "30",
    borderColor: themes.white + "20",
    opacity: 0.6,
  },
  actionButtonTitle: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.white,
    marginTop: 12,
    textAlign: "center",
  },
  actionButtonTitleDisabled: {
    color: themes.white + "60",
  },
  actionButtonSubtitle: {
    fontSize: 16,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    marginTop: 4,
    textAlign: "center",
  },
  actionButtonSubtitleDisabled: {
    color: themes.white + "40",
  },
  noSelectionContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(201, 176, 55, 0.05)",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: themes.vegasGold + "30",
    borderStyle: "dashed",
  },
  noSelectionText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.7,
    textAlign: "center",
    marginTop: 12,
    lineHeight: 22,
  },
  loadingContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    height: 200,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.8,
  },
  errorContainer: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
    height: 200,
  },
  errorText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: "#FF4444",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 22,
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: themes.vegasGold,
    borderRadius: 8,
  },
  retryButtonText: {
    fontSize: 16,
    fontFamily: "Chakra-Bold",
    color: themes.black,
  },
  emptyListContainer: {
    width: 280,
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyListText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    textAlign: "center",
    color: themes.white,
    opacity: 0.7,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: themes.black,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: themes.vegasGold + "30",
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: themes.vegasGold + "20",
    alignItems: "center",
    justifyContent: "center",
  },
  closeButtonPlaceholder: {
    width: 40,
  },
  modalTitleSection: {
    flex: 1,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.white,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes.white + "70",
    marginTop: 4,
  },
  modalContent: {
    flex: 1,
    paddingHorizontal: 20,
  },
  emptyStateModal: {
    padding: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyStateTitle: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.white,
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white + "70",
    textAlign: "center",
    lineHeight: 22,
  },
  videoItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    marginVertical: 6,
    backgroundColor: themes.black + "60",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold + "30",
  },
  videoIcon: {
    marginRight: 16,
  },
  videoContent: {
    flex: 1,
  },
  videoTitle: {
    fontSize: 16,
    fontFamily: "Chakra-Bold",
    color: themes.white,
    marginBottom: 4,
  },
  videoDescription: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes.white + "80",
    marginBottom: 8,
    lineHeight: 18,
  },
  videoMeta: {
    flexDirection: "row",
    gap: 12,
  },
  videoOrder: {
    fontSize: 12,
    fontFamily: "Chakra-Regular",
    color: themes.vegasGold,
    fontWeight: "600",
  },
  videoWeek: {
    fontSize: 12,
    fontFamily: "Chakra-Regular",
    color: themes.vegasGold + "80",
    fontWeight: "600",
  },
  studentItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    marginVertical: 6,
    backgroundColor: themes.black + "60",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold + "30",
  },
  studentInfo: {
    flex: 1,
  },
  studentName: {
    fontSize: 16,
    fontFamily: "Chakra-Bold",
    color: themes.white,
    marginBottom: 4,
  },
  studentCourse: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes.vegasGold,
    marginBottom: 8,
  },
  progressInfo: {
    marginBottom: 8,
  },
  progressBar: {
    height: 6,
    backgroundColor: themes.white + "20",
    borderRadius: 3,
    marginBottom: 4,
  },
  progressFill: {
    height: "100%",
    backgroundColor: themes.vegasGold,
    borderRadius: 3,
  },
  progressText: {
    fontSize: 12,
    fontFamily: "Chakra-Regular",
    color: themes.white + "80",
  },
  studentNotes: {
    fontSize: 12,
    fontFamily: "Chakra-Regular",
    color: themes.white + "70",
    fontStyle: "italic",
  },
  updateButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: themes.vegasGold,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },

  // Student Progress Modal Styles
  filterSection: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: themes.vegasGold + '20',
  },
  filterTitle: {
    fontSize: 16,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
    marginBottom: 8,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filterButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 8,
    marginHorizontal: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.vegasGold + '40',
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  filterButtonActive: {
    backgroundColor: themes.vegasGold + '30',
    borderColor: themes.vegasGold,
  },
  filterButtonText: {
    fontSize: 12,
    fontFamily: "Chakra-Regular",
    color: themes.white + '80',
  },
  filterButtonTextActive: {
    color: themes.vegasGold,
    fontFamily: "Chakra-Bold",
  },
  progressStatusRow: {
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
  },
  studentHeaderRow: {
    flexDirection: 'row', 
    alignItems: 'center', 
    marginBottom: 4,
  },
  updateButtonDisabled: {
    backgroundColor: themes.white + '30',
    opacity: 0.5,
  },
});
