import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const masterAdminCourseManagementStyles = StyleSheet.create({
  container: {
    flex:  1,
    flexDirection: "column",
  },
  safeArea: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    backgroundColor: "transparent",
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  pageTitle: {
    marginBottom: 24,
    textAlign: "center",
    fontSize: 34,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
  },
  loadingContainer: {
    flex:  1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  errorText: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: "#FF4444",
    textAlign: "center",
    marginBottom: 20,
  },
  retryButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: themes.vegasGold,
    borderRadius: 6,
  },
  retryButtonText:  {
    fontSize: 16,
    fontFamily: "Chakra-Medium",
    color: themes.black,
  },
  courseSection: {
    flex: 1,
    paddingHorizontal: 12,
    backgroundColor: "transparent",
  },
  selectedBanner: {
    marginHorizontal: 8,
    marginTop: 16,
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black + "60",
  },
  selectedBannerLabel: {
    fontSize: 12,
    fontFamily: "Chakra-Regular",
    color: themes.vegasGold,
    opacity: 0.9,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  selectedBannerTitle: {
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  selectedBannerPlaceholder: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.6,
  },
  buttonContainer: {
    flexDirection: "column",
    marginBottom: 16,
  },
  createCourseButton: {
    alignItems: "center",
    padding: 14,
    marginHorizontal: 8,
    marginTop: 16,
    marginBottom: 8,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: themes.vegasGold,
    backgroundColor: "transparent",
  },
  createCourseButtonText: {
    fontSize: 20,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
  },
  contextActionsLabel: {
    fontSize: 13,
    fontFamily: "Chakra-Medium",
    color: themes.vegasGold,
    opacity: 0.95,
    marginLeft: 16,
    marginBottom: 8,
    marginTop: 4,
  },
  contextButtonRow: {
    flexDirection: "column",
  },
  actionButton: {
    alignItems: "center",
    padding: 12,
    marginHorizontal: 8,
    marginVertical: 6,
    borderRadius: 15,
    backgroundColor: themes.vegasGold,
  },
  buttonText: {
    fontSize: 20,
    fontFamily: "Chakra-BoldItalic",
    color: themes.white,
  },
});