import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const videoManagementModalStyles = StyleSheet.create({
  modalOverlay: {
    flex:  1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  modalContent: {
    width: "80%",
    alignSelf: "center",
    padding: 20,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: themes. vegasGold,
    backgroundColor:  themes.black,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    marginBottom: 16,
    textAlign: "center",
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  inputDescription: {
    fontSize: 16,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 20,
    opacity: 0.9,
  },
  confirmButton: {
    flex: 1,
    padding: 12,
    marginLeft: 12,
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  buttonText: {
    fontSize: 24,
    fontFamily: "Chakra-BoldItalic",
    color: themes.white,
  },
  tableContainer: {
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
  emptyStateTitle: {
    fontSize:  20,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
    textAlign: "center",
    marginBottom: 12,
  },
  emptyStateDescription: {
    fontSize:  16,
    fontFamily:  "Chakra-Regular",
    color: themes.white,
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 24,
    opacity: 0.9,
  },
  listContent: {
    paddingBottom: 16,
  },
  separator:  {
    height: 1,
    backgroundColor: themes.vegasGold,
  },
  row: {
    flex: 1,
    flexDirection: "row",
    padding: 16,
    alignItems: "center",
  },
  info: {
    flex: 3,
  },
  name: {
    marginBottom: 4,
    fontSize: 24,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  description: {
    marginBottom: 8,
    fontSize: 18,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    opacity: 0.8,
  },
  details: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  badge: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    marginRight: 12,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
  },
  badgeText: {
    fontSize: 18,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  actions: {
    flex: 1,
    flexDirection: "column",
  },
  actionButton: {
    flex: 1,
    alignItems: "center",
    padding: 12,
    margin: 8,
    borderRadius: 15,
    backgroundColor: themes.vegasGold,
  },
  actionText: {
    marginLeft: 6,
    fontSize: 14,
    fontFamily: "Chakra-BoldItalic",
    color: themes.vegasGold,
  },
  removeText: {
    color: "#FF4444",
  },
  footerInfo: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: themes.vegasGold,
  },
  footerText: {
    fontSize: 12,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    textAlign: "center",
    lineHeight: 16,
  },
});