import { themes } from "@/src/context/themes";
import { StyleSheet, Platform } from "react-native";

export const registerScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  backButtonContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 10 : 0,
    paddingBottom: 10,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  registerScreenContentContainer: {
    flexDirection: "column",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  image: {
    width: 120,
    height: 100,
    resizeMode: "contain",
    marginBottom: 8,
  },
  welcomeContainer: {
    marginBottom: 24,
    marginHorizontal: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  welcomeText: {
    textAlign: "center",
    marginBottom: 6,
    letterSpacing: 0.5,
    fontSize: 22,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  welcomeSubtext: {
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  formContainer: {
    width: "100%",
    gap: 16,
    alignItems: "center",
  },
  nameInputBoxContainer: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
    justifyContent: "center",
  },
  nameInputBox: {
    flex: 1,
    height: 52,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
    color: themes.vegasGold,
    fontSize: 16,
    fontFamily: "Chakra-Italic",
  },
  textInputBox: {
    width: "100%",
    height: 52,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themes.vegasGold,
    backgroundColor: themes.black,
    color: themes.vegasGold,
    fontSize: 16,
    fontFamily: "Chakra-Italic",
  },
  signUpButton: {
    width: "100%",
    height: 54,
    marginTop: 8,
    backgroundColor: themes.vegasGold,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  signUpButtonText: {
    fontFamily: "Chakra-semiBoldItalic",
    fontSize: 20,
    color: themes.white,
  },
});