import { themes } from "@/src/context/themes";
import { StyleSheet } from "react-native";

export const registerScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    paddingHorizontal: 16,
    paddingVertical: 8,
    justifyContent: "center",
  },
  card: {
    width: "100%",
    maxWidth: 620,
    alignSelf: "center",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(197,179,88,0.3)",
    backgroundColor: "rgba(8,8,8,0.78)",
    paddingTop: 24,
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 12,
  },
  backButtonContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  registerScreenContentContainer: {
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
  },
  image: {
    width: 72,
    height: 72,
    resizeMode: "contain",
    borderRadius: 12,
  },
  brandHeader: {
    alignItems: "center",
    gap: 6,
  },
  title: {
    textAlign: "center",
  },
  subtitle: {
    textAlign: "center",
    color: themes.textSecondary,
  },
  flowBadge: {
    borderWidth: 1,
    borderColor: "rgba(197,179,88,0.34)",
    borderRadius: 999,
    backgroundColor: "rgba(197,179,88,0.1)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 4,
  },
  flowBadgeText: {
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  welcomeContainer: {
    width: "100%",
    marginBottom: 10,
    marginHorizontal: 0,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.borderStrong,
    backgroundColor: "rgba(197,179,88,0.08)",
  },
  welcomeText: {
    textAlign: "center",
    marginBottom: 6,
    letterSpacing: 0.5,
    fontSize: 24,
    fontFamily: "Oswald_500Medium",
    color: themes.white,
  },
  welcomeSubtext: {
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    fontFamily: "Inter_400Regular",
    color: themes.textSecondary,
  },
  formContainer: {
    width: "100%",
    gap: 12,
    alignItems: "center",
  },
  nameInputBoxContainer: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
    justifyContent: "center",
  },
  nameInputBox: {
    flex: 1,
    height: 52,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themes.borderStrong,
    backgroundColor: themes.backgroundElevated,
    color: themes.textPrimary,
    fontSize: 16,
    fontFamily: "Inter_400Regular",
  },
  textInputBox: {
    width: "100%",
    height: 52,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themes.borderStrong,
    backgroundColor: themes.backgroundElevated,
    color: themes.textPrimary,
    fontSize: 16,
    fontFamily: "Inter_400Regular",
  },
  signUpButton: {
    width: "100%",
    height: 54,
    marginTop: 8,
    backgroundColor: themes.vegasGold,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  signUpButtonText: {
    fontFamily: "Oswald_500Medium",
    fontSize: 18,
    color: themes.black,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
});