import { StyleSheet } from "react-native";
import { themes } from "@/src/context/themes";

export const roleSelectionModalStyles = StyleSheet.create({
  modalOverlay: {
    flex:  1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  modalContent: {
    width: "85%",
    maxWidth: 450,
    padding: 20,
    backgroundColor:  themes.black,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: themes.vegasGold,
  },
  modalTitle: {
    marginBottom: 20,
    fontSize: 28,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
    textAlign: "center",
  },
  welcomeContainer: {
    marginVertical: 20,
    marginHorizontal: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  welcomeTitle: {
    textAlign: "center",
    marginBottom: 8,
    fontSize: 20,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  welcomeText: {
    textAlign: "center",
    marginBottom: 8,
    letterSpacing: 0.5,
    fontSize: 32,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  companyName: {
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  welcomeSubtext:  {
    textAlign: "center",
    fontSize: 20,
    fontFamily: "Chakra-Regular",
    color: themes.white,
  },
  buttonContainer: {
    gap: 16,
    marginBottom: 20,
  },
  roleButton: {
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 15,
    backgroundColor: themes.vegasGold,
    borderWidth: 1,
    borderColor: themes. vegasGold,
  },
  recommendedButton: {
    backgroundColor: themes.vegasGold,
    borderWidth: 2,
    borderColor: themes. vegasGold,
    shadowColor: themes.vegasGold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity:  0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  disabledButton: {
    opacity: 0.6,
  },
  buttonContent: {
    alignItems: "center",
    width: "100%",
  },
  buttonHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    gap: 12,
  },
  buttonTitle: {
    fontSize: 22,
    fontFamily: "Chakra-Bold",
    color: themes.white,
  },
  buttonDescription: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes.white,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 8,
  },
  recommendedBadge:  {
    backgroundColor: themes.black,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themes.vegasGold,
  },
  recommendedText: {
    fontSize: 12,
    fontFamily: "Chakra-Bold",
    color: themes.vegasGold,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    gap: 8,
  },
  loadingText: {
    fontSize: 14,
    fontFamily: "Chakra-Regular",
    color: themes. white,
  },
  footerInfo: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: themes.vegasGold,
  },
  footerText: {
    fontSize: 12,
    fontFamily: "Chakra-Italic",
    color: themes.white,
    textAlign: "center",
    lineHeight: 16,
  },
});